import { FunctionComponent } from "react";
import "antd/dist/reset.css";
import { AutoComplete } from "antd";
import Stripe from "../components/Stripe";
import ProfileHeader from "../components/ProfileHeader";
import Diagramleft from "../components/Diagram1";
import DiagramRight from "../components/Diagram2";
import Calendar from "../components/Calendar";
import Footer from "../components/Footer";
import logo from "../public/-11-1@2x.png"


const Frame5: FunctionComponent = () => {
  return (
    <div className="w-full h-[89.188rem] relative bg-[#f0f4f9] overflow-hidden flex flex-col items-end justify-start pt-[2.187rem] pb-[3.125rem] pl-[6.25rem] pr-[6.312rem] box-border gap-[22.375rem] leading-[normal] tracking-[normal] mq750:gap-[11.188rem] mq750:pl-[3.125rem] mq750:pr-[3.125rem] mq750:box-border mq1050:h-auto mq450:gap-[5.563rem] mq450:pl-[1.25rem] mq450:pr-[1.25rem] mq450:box-border">
      <main className="self-stretch flex flex-row items-start justify-start gap-[3.75rem] shrink-0 max-w-full lg:gap-[1.875rem]">
        <div className="w-[7.5rem] flex flex-col items-start justify-start pt-[0.062rem] px-[0rem] pb-[0rem] box-border mq750:hidden">
          <div className="self-stretch h-[68.75rem] relative">
            <Stripe />
            <img
              className="absolute top-[2.125rem] left-[1.125rem] w-[5.188rem] h-[5.188rem] object-cover z-[1]"
              loading="lazy"
              alt=""
              src={logo} // замість src="/-11-1@2x.png"
            />
          </div>
        </div>
        <section className="flex-1 flex flex-row items-start justify-start relative max-w-[calc(100%_-_11.25rem)] text-left text-[1rem] text-[#444] font-[Inter] mq750:max-w-full">
          <b className="absolute !m-[0] bottom-[27.563rem] left-[1.125rem] inline-block z-[1]">
            Мої співпраці 2024рік
          </b>
          <ProfileHeader
            profilePicture="/ellipse-1@2x.png"
            group95="/group-95.svg"
          />
          
          <div className="flex-1 flex flex-col items-end justify-start gap-[5.875rem] max-w-full text-[1.25rem] text-[#000] mq750:gap-[1.438rem] mq1050:gap-[2.938rem]">
            <AutoComplete
              className=" w-[23.938rem] h-[17.375rem] top-[-80rem] left-[30.875rem] z-[0]"
              style={{ width: '383px' }}
            />
            //body
            <div className="self-stretch flex flex-row items-start justify-end py-[0rem] pl-[0.875rem] pr-[1.937rem] box-border max-w-full">
              <div className="flex-1 flex flex-col items-end justify-start gap-[6.437rem] max-w-full mq750:gap-[1.625rem] mq1050:gap-[3.188rem]">
                <div className="self-stretch flex flex-row items-start justify-end py-[0rem] pl-[0rem] pr-[0.812rem] box-border max-w-full">
                  <div className="flex-1 flex flex-row items-start justify-start gap-[2rem] max-w-full mq1050:flex-wrap mq450:gap-[1rem]">
                    <div className="flex-1 flex flex-row items-start justify-start relative min-w-[18.188rem] max-w-full mq1050:flex-1">
                      <div className="h-[85.5rem] w-[63.5rem] absolute !m-[0] right-[-32.687rem] bottom-[-49.687rem]">
                        <img
                          className="absolute top-[0rem] left-[3.3rem] rounded-[2.5rem] w-full h-full"
                          alt=""
                          src="/bg.svg"
                        />
                        <img
                          className="absolute top-[38.938rem] left-[17rem] rounded-[0.3125rem] w-[7.438rem] h-[8.75rem] object-cover z-[1]"
                          loading="lazy"
                          alt=""
                          src="/rectangle-58@2x.png"
                        />
                        <img
                          className="absolute top-[38.938rem] left-[25.2rem] rounded-[0.3125rem] w-[7.5rem] h-[8.75rem] object-cover z-[1]"
                          loading="lazy"
                          alt=""
                          src="/rectangle-59@2x.png"
                        />
                        <img
                          className="absolute top-[38.938rem] left-[33.4rem] rounded-[0.3125rem] w-[7.438rem] h-[8.75rem] object-cover z-[1]"
                          loading="lazy"
                          alt=""
                          src="/rectangle-60@2x.png"
                        />
                        <div className="absolute top-[38.938rem] left-[41.5rem] w-[7.5rem] flex flex-row items-start justify-start">
                          <img
                            className="h-[8.75rem] flex-1 relative rounded-[0.3125rem] max-w-full overflow-hidden object-cover z-[1]"
                            alt=""
                            src="/play-button@2x.png"
                          />
                          <img
                            className="h-[1.5rem] w-[1.5rem] absolute !m-[0] top-[calc(50%_-_0.75rem)] right-[2.938rem] object-cover z-[2]"
                            loading="lazy"
                            alt=""
                            src="/actions--controls--playoutline--26@2x.png"
                          />
                        </div>
                        <img
                          className="absolute top-[38.938rem] left-[49.775rem] rounded-[0.3125rem] w-[7.438rem] h-[8.75rem] object-cover z-[1]"
                          loading="lazy"
                          alt=""
                          src="/rectangle-62@2x.png"
                        />
                      </div>
                      <Diagramleft />
                    </div>
                    <DiagramRight group107="/group-107.svg" />
                  </div>
                </div>
                <div className="w-[47.563rem] flex flex-row items-start justify-start relative max-w-full">
                  <div className="absolute !m-[0] top-[0.313rem] right-[4.438rem] inline-block min-w-[4.063rem] z-[2] mq450:text-[1rem]">
                    4493+
                  </div>
                  <div className="flex-1 flex flex-col items-end justify-start gap-[4.375rem] max-w-full text-[0.75rem] text-[#444] mq1050:gap-[2.188rem] mq450:gap-[1.063rem]">
                    <img
                      className="w-[2rem] h-[2rem] relative object-contain z-[1]"
                      alt=""
                      src="/actions--navigation--chevronleft--33.svg"
                    />
                    <div className="self-stretch flex flex-row items-start justify-start max-w-full">
                      <div className="w-[39.938rem] flex flex-row items-start justify-between py-[0rem] pl-[7rem] pr-[0.187rem] box-border gap-[1.25rem] max-w-full mq450:flex-wrap">
                        <div className="flex flex-row items-start justify-start py-[0rem] pl-[-10rem] pr-[0.312rem] gap-[0.312rem]">
                          <div className="flex flex-col items-start justify-start pt-[0.125rem] px-[0rem] pb-[0rem]">
                            <div className="flex flex-col items-start justify-start gap-[0.625rem]">
                              <img
                                className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                loading="lazy"
                                alt=""
                                src="/actions--toggle--favorite--241@2x.png"
                              />
                              <img
                                className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                loading="lazy"
                                alt=""
                                src="/actions--operations--bookmark--24@2x.png"
                              />
                            </div>
                          </div>
                          <div className="flex flex-col items-start justify-start gap-[0.25rem]">
                            <div className="relative inline-block min-w-[1rem] z-[1]">
                              5К
                            </div>
                            <div className="relative inline-block min-w-[1.313rem] z-[1]">
                              130
                            </div>
                          </div>
                        </div>
                        <div className="flex flex-row items-start justify-start gap-[0.312rem]">
                          <div className="flex flex-col items-start justify-start pt-[0.125rem] px-[0rem] pb-[0rem]  pl-[3rem]">
                            <div className="flex flex-col items-start justify-start gap-[0.625rem]">
                              <img
                                className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                alt=""
                                src="/actions--toggle--favorite--241@2x.png"
                              />
                              <img
                                className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                alt=""
                                src="/actions--operations--bookmark--24@2x.png"
                              />
                            </div>
                          </div>
                          <div className="flex flex-col items-start justify-start gap-[0.25rem]">
                            <div className="relative inline-block min-w-[1.625rem] z-[1]">
                              4.3К
                            </div>
                            <div className="relative inline-block min-w-[1.313rem] z-[1]">
                              100
                            </div>
                          </div>
                        </div>
                        <div className="flex flex-col items-start justify-start pt-[0.062rem] pl-[5rem] px-[0rem] pb-[0rem]">
                          <div className="flex flex-col items-start justify-start gap-[0.25rem]">
                            <div className="flex flex-col items-start justify-start gap-[0.25rem]">
                              <div className="flex flex-row items-start justify-start gap-[0.312rem]">
                                <div className="flex flex-col items-start justify-start pt-[0.125rem] px-[0rem] pb-[0rem]">
                                  <img
                                    className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                    alt=""
                                    src="/actions--toggle--favorite--241@2x.png"
                                  />
                                </div>
                                <div className="relative inline-block min-w-[1.5rem] z-[1]">
                                  1.3К
                                </div>
                              </div>
                              <div className="flex flex-row items-start justify-start gap-[0.312rem]">
                                <div className="flex flex-col items-start justify-start pt-[0.187rem] px-[0rem] pb-[0rem]">
                                  <img
                                    className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                    alt=""
                                    src="/actions--operations--bookmark--24@2x.png"
                                  />
                                </div>
                                <div className="relative inline-block min-w-[1.313rem] z-[1]">
                                  100
                                </div>
                              </div>
                            </div>
                            <div className="flex flex-row items-start justify-start gap-[0.312rem]">
                              <div className="flex flex-col items-start justify-start pt-[0.187rem] px-[0rem] pb-[0rem]">
                                <img
                                  className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                  alt=""
                                  src="/actions--toggle--view--24@2x.png"
                                />
                              </div>
                              <div className="relative inline-block min-w-[1.625rem] z-[1]">
                                5.3К
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="flex flex-col items-start justify-start pl-[5rem] pt-[0.062rem] px-[0rem] pb-[0rem]">
                          <div className="flex flex-col items-start justify-start gap-[0.25rem]">
                            <div className="flex flex-col items-start justify-start gap-[0.25rem]">
                              <div className="flex flex-row items-start justify-start gap-[0.312rem]">
                                <div className="flex flex-col items-start justify-start pt-[0.125rem] px-[0rem] pb-[0rem]">
                                  <img
                                    className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                    alt=""
                                    src="/actions--toggle--favorite--241@2x.png"
                                  />
                                </div>
                                <div className="relative inline-block min-w-[1.5rem] z-[1]">
                                  1.3К
                                </div>
                              </div>
                              <div className="flex flex-row items-start justify-start gap-[0.312rem]">
                                <div className="flex flex-col items-start justify-start pt-[0.187rem] px-[0rem] pb-[0rem]">
                                  <img
                                    className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                    alt=""
                                    src="/actions--operations--bookmark--24@2x.png"
                                  />
                                </div>
                                <div className="relative inline-block min-w-[1.313rem] z-[1]">
                                  100
                                </div>
                              </div>
                            </div>
                            <div className="flex flex-row items-start justify-start gap-[0.25rem]">
                              <div className="flex flex-col items-start justify-start pt-[0.187rem] px-[0rem] pb-[0rem]">
                                <img
                                  className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                  alt=""
                                  src="/actions--toggle--view--24@2x.png"
                                />
                              </div>
                              <div className="relative inline-block min-w-[1.625rem] z-[1]">
                                5.3К
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="flex flex-col items-start justify-start pt-[0.062rem] pl-[5rem] px-[0rem] pb-[0rem]">
                          <div className="flex flex-row items-start justify-start gap-[0.312rem]">
                            <div className="flex flex-col items-start justify-start pt-[0.125rem] px-[0rem] pb-[0rem]">
                              <div className="flex flex-col items-start justify-start gap-[0.75rem]">
                                <img
                                  className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                  alt=""
                                  src="/actions--toggle--favorite--241@2x.png"
                                />
                                <img
                                  className="w-[0.625rem] h-[0.625rem] relative object-cover z-[1]"
                                  alt=""
                                  src="/actions--operations--bookmark--24@2x.png"
                                />
                              </div>
                            </div>
                            <div className="flex flex-col items-start justify-start gap-[0.375rem]">
                              <div className="relative inline-block min-w-[1.625rem] z-[1]">
                                4.3К
                              </div>
                              <div className="relative inline-block min-w-[1.313rem] z-[1]">
                                100
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="self-stretch flex flex-row items-start justify-end py-[0rem] pl-[0rem] pr-[1.937rem] box-border max-w-full">
              <div className="flex-1 flex flex-col items-start justify-start gap-[3.937rem] max-w-full mq750:gap-[1rem] mq1050:gap-[1.938rem]">
                <div className="self-stretch flex flex-row items-start justify-start gap-[1.875rem] lg:flex-wrap">
                  <Calendar
                    propMinWidth="unset"
                    prop="Березень"
                    propMinWidth1="1.938rem"
                    propMinWidth2="1.938rem"
                    propMinWidth3="1.938rem"
                    propMinWidth4="1.938rem"
                    propMinWidth5="1.938rem"
                    propMinWidth6="1.938rem"
                    propMinWidth7="1.938rem"
                    prop1="1"
                    prop2="2"
                    prop3="3"
                    prop4="4"
                    prop5="5"
                    prop6="6"
                    prop7="7"
                    prop8="8"
                    prop9="9"
                    prop10="10"
                    prop11="11"
                    prop12="12"
                    prop13="13"
                    prop14="14"
                    prop15="15"
                    prop16="16"
                    prop17="17"
                    prop18="18"
                    prop19="19"
                    prop20="20"
                    prop21="21"
                    prop22="22"
                    prop23="23"
                    prop24="24"
                    prop25="25"
                    prop26="26"
                    prop27="27"
                    prop28="28"
                    prop29="29"
                    prop30="30"
                    prop31="31"
                    prop32="1"
                    prop33="1"
                    prop34="1"
                    propWidth="unset"
                    propWidth1="unset"
                    propWidth2="unset"
                    propWidth3="unset"
                    propWidth4="unset"
                    propWidth5="unset"
                    propWidth6="unset"
                    propWidth7="unset"
                    propWidth8="unset"
                    propWidth9="unset"
                    propWidth10="unset"
                    propWidth11="unset"
                    propWidth12="unset"
                    propWidth13="unset"
                    propWidth14="unset"
                    propWidth15="unset"
                    propWidth16="unset"
                    propWidth17="unset"
                    propWidth18="unset"
                    propWidth19="unset"
                    propWidth20="unset"
                    propWidth21="unset"
                    propWidth22="unset"
                    propWidth23="unset"
                    propWidth24="unset"
                    propWidth25="unset"
                    propWidth26="unset"
                    propWidth27="unset"
                    propWidth28="1.5rem"
                    propWidth29="1.5rem"
                    propWidth30="1.5rem"
                    propWidth31="1.5rem"
                    propWidth32="1.5rem"
                    propWidth33="1.5rem"
                    propFlex="1"
                    propFlex1="1"
                    propFlex2="1"
                    propFlex3="1"
                    propFlex4="1"
                    propFlex5="1"
                    propFlex6="1"
                    propFlex7="1"
                    propFlex8="1"
                    propFlex9="1"
                    propFlex10="1"
                    propFlex11="1"
                    propFlex12="1"
                    propFlex13="1"
                    propFlex14="1"
                    propFlex15="1"
                    propFlex16="1"
                    propFlex17="1"
                    propFlex18="1"
                    propFlex19="1"
                    propFlex20="1"
                    propFlex21="1"
                    propFlex22="1"
                    propFlex23="1"
                    propFlex24="1"
                    propFlex25="1"
                    propFlex26="1"
                    propFlex27="1"
                    propFlex28="unset"
                    propFlex29="unset"
                    propFlex30="unset"
                    propFlex31="unset"
                    propFlex32="unset"
                    propFlex33="unset"
                    propBorderRadius="2.5rem"
                    propBorderRadius1="unset"
                    propBorderRadius2="unset"
                    propBorderRadius3="2.5rem"
                    propBorderRadius4="2.5rem"
                    propBorderRadius5="unset"
                    propBorderRadius6="unset"
                    propBorderRadius7="2.5rem"
                    propBorderRadius8="2.5rem"
                    propBorderRadius9="2.5rem"
                    propBorderRadius10="unset"
                    propBorderRadius11="unset"
                    propBorderRadius12="2.5rem"
                    propBorderRadius13="unset"
                    propBorderRadius14="2.5rem"
                    propBorderRadius15="2.5rem"
                    propBorderRadius16="unset"
                    propBorderRadius17="unset"
                    propBorderRadius18="2.5rem"
                    propBorderRadius19="unset"
                    propBorderRadius20="unset"
                    propBorderRadius21="unset"
                    propBorderRadius22="unset"
                    propBorderRadius23="unset"
                    propBorderRadius24="unset"
                    propBorderRadius25="unset"
                    propBorderRadius26="unset"
                    propBorderRadius27="unset"
                    propBorderRadius28="unset"
                    propBorderRadius29="unset"
                    propBorderRadius30="unset"
                    propBorderRadius31="unset"
                    propBorderRadius32="unset"
                    propBorderRadius33="unset"
                    propBackgroundColor="#009ea0"
                    propBackgroundColor1="unset"
                    propBackgroundColor2="unset"
                    propBackgroundColor3="#009ea0"
                    propBackgroundColor4="#009ea0"
                    propBackgroundColor5="unset"
                    propBackgroundColor6="unset"
                    propBackgroundColor7="#009ea0"
                    propBackgroundColor8="#f6a801"
                    propBackgroundColor9="#009ea0"
                    propBackgroundColor10="unset"
                    propBackgroundColor11="unset"
                    propBackgroundColor12="#009ea0"
                    propBackgroundColor13="unset"
                    propBackgroundColor14="#009ea0"
                    propBackgroundColor15="#009ea0"
                    propBackgroundColor16="unset"
                    propBackgroundColor17="unset"
                    propBackgroundColor18="#009ea0"
                    propBackgroundColor19="unset"
                    propBackgroundColor20="unset"
                    propBackgroundColor21="unset"
                    propBackgroundColor22="unset"
                    propBackgroundColor23="unset"
                    propBackgroundColor24="unset"
                    propBackgroundColor25="unset"
                    propBackgroundColor26="unset"
                    propBackgroundColor27="unset"
                    propBackgroundColor28="unset"
                    propBackgroundColor29="unset"
                    propBackgroundColor30="unset"
                    propBackgroundColor31="unset"
                    propBackgroundColor32="unset"
                    propBackgroundColor33="unset"
                    propOverflow="hidden"
                    propOverflow1="unset"
                    propOverflow2="unset"
                    propOverflow3="hidden"
                    propOverflow4="hidden"
                    propOverflow5="unset"
                    propOverflow6="unset"
                    propOverflow7="hidden"
                    propOverflow8="unset"
                    propOverflow9="hidden"
                    propOverflow10="unset"
                    propOverflow11="unset"
                    propOverflow12="hidden"
                    propOverflow13="unset"
                    propOverflow14="hidden"
                    propOverflow15="hidden"
                    propOverflow16="unset"
                    propOverflow17="unset"
                    propOverflow18="hidden"
                    propOverflow19="unset"
                    propOverflow20="unset"
                    propOverflow21="unset"
                    propOverflow22="unset"
                    propOverflow23="unset"
                    propOverflow24="unset"
                    propOverflow25="unset"
                    propOverflow26="unset"
                    propOverflow27="unset"
                    propOverflow28="unset"
                    propOverflow29="unset"
                    propOverflow30="unset"
                    propOverflow31="unset"
                    propOverflow32="unset"
                    propOverflow33="unset"
                    propColor="#fdfdfd"
                    propColor1="#3c3c3c"
                    propColor2="#3c3c3c"
                    propColor3="#fdfdfd"
                    propColor4="#fdfdfd"
                    propColor5="#3c3c3c"
                    propColor6="#3c3c3c"
                    propColor7="#fdfdfd"
                    propColor8="#fff"
                    propColor9="#fdfdfd"
                    propColor10="#3c3c3c"
                    propColor11="#3c3c3c"
                    propColor12="#fdfdfd"
                    propColor13="#3c3c3c"
                    propColor14="#fdfdfd"
                    propColor15="#fdfdfd"
                    propColor16="#3c3c3c"
                    propColor17="#3c3c3c"
                    propColor18="#fdfdfd"
                    propColor19="#3c3c3c"
                    propColor20="#3c3c3c"
                    propColor21="#3c3c3c"
                    propColor22="#3c3c3c"
                    propColor23="#3c3c3c"
                    propColor24="#3c3c3c"
                    propColor25="#3c3c3c"
                    propColor26="#3c3c3c"
                    propColor27="#3c3c3c"
                    propColor28="#3c3c3c"
                    propColor29="#3c3c3c"
                    propColor30="#3c3c3c"
                    propColor31="rgba(60, 60, 60, 0)"
                    propColor32="rgba(60, 60, 60, 0)"
                    propColor33="rgba(60, 60, 60, 0)"
                    propTextShadow="unset"
                    propTextShadow1="unset"
                    propTextShadow2="unset"
                    propTextShadow3="unset"
                    propTextShadow4="unset"
                    propTextShadow5="unset"
                    propTextShadow6="unset"
                    propTextShadow7="unset"
                    propTextShadow8="0rem 0.25rem 0.25rem rgba(0, 0, 0, 0.25)"
                    propTextShadow9="unset"
                    propTextShadow10="unset"
                    propTextShadow11="unset"
                    propTextShadow12="unset"
                    propTextShadow13="unset"
                    propTextShadow14="unset"
                    propTextShadow15="unset"
                    propTextShadow16="unset"
                    propTextShadow17="unset"
                    propTextShadow18="unset"
                    propTextShadow19="unset"
                    propTextShadow20="unset"
                    propTextShadow21="unset"
                    propTextShadow22="unset"
                    propTextShadow23="unset"
                    propTextShadow24="unset"
                    propTextShadow25="unset"
                    propTextShadow26="unset"
                    propTextShadow27="unset"
                    propTextShadow28="unset"
                    propTextShadow29="unset"
                    propTextShadow30="unset"
                    propTextShadow31="unset"
                    propTextShadow32="unset"
                    propTextShadow33="unset"
                    propTextDecoration="unset"
                    propTextDecoration1="unset"
                    propTextDecoration2="unset"
                    propTextDecoration3="unset"
                    propTextDecoration4="unset"
                    propTextDecoration5="unset"
                    propTextDecoration6="unset"
                    propTextDecoration7="unset"
                    propTextDecoration8="unset"
                    propTextDecoration9="unset"
                    propTextDecoration10="unset"
                    propTextDecoration11="unset"
                    propTextDecoration12="unset"
                    propTextDecoration13="unset"
                    propTextDecoration14="unset"
                    propTextDecoration15="none"
                    propTextDecoration16="none"
                    propTextDecoration17="unset"
                    propTextDecoration18="unset"
                    propTextDecoration19="unset"
                    propTextDecoration20="unset"
                    propTextDecoration21="unset"
                    propTextDecoration22="unset"
                    propTextDecoration23="unset"
                    propTextDecoration24="unset"
                    propTextDecoration25="unset"
                    propTextDecoration26="unset"
                    propTextDecoration27="unset"
                    propTextDecoration28="unset"
                    propTextDecoration29="unset"
                    propTextDecoration30="unset"
                    propTextDecoration31="unset"
                    propTextDecoration32="unset"
                    propTextDecoration33="unset"
                  />
                  <Calendar
                    propMinWidth="unset"
                    prop="квітень"
                    propMinWidth1="1.938rem"
                    propMinWidth2="1.938rem"
                    propMinWidth3="1.938rem"
                    propMinWidth4="1.938rem"
                    propMinWidth5="1.938rem"
                    propMinWidth6="1.938rem"
                    propMinWidth7="1.938rem"
                    prop1="1"
                    prop2="2"
                    prop3="3"
                    prop4="4"
                    prop5="5"
                    prop6="6"
                    prop7="7"
                    prop8="8"
                    prop9="9"
                    prop10="10"
                    prop11="11"
                    prop12="12"
                    prop13="13"
                    prop14="14"
                    prop15="15"
                    prop16="16"
                    prop17="17"
                    prop18="18"
                    prop19="19"
                    prop20="20"
                    prop21="21"
                    prop22="22"
                    prop23="23"
                    prop24="24"
                    prop25="25"
                    prop26="26"
                    prop27="27"
                    prop28="28"
                    prop29="29"
                    prop30="30"
                    prop31="31"
                    prop32="1"
                    prop33="1"
                    prop34="1"
                    propWidth="unset"
                    propWidth1="unset"
                    propWidth2="unset"
                    propWidth3="unset"
                    propWidth4="unset"
                    propWidth5="unset"
                    propWidth6="unset"
                    propWidth7="unset"
                    propWidth8="unset"
                    propWidth9="unset"
                    propWidth10="unset"
                    propWidth11="unset"
                    propWidth12="unset"
                    propWidth13="unset"
                    propWidth14="unset"
                    propWidth15="unset"
                    propWidth16="unset"
                    propWidth17="unset"
                    propWidth18="unset"
                    propWidth19="unset"
                    propWidth20="unset"
                    propWidth21="unset"
                    propWidth22="unset"
                    propWidth23="unset"
                    propWidth24="unset"
                    propWidth25="unset"
                    propWidth26="unset"
                    propWidth27="unset"
                    propWidth28="1.5rem"
                    propWidth29="1.5rem"
                    propWidth30="1.5rem"
                    propWidth31="1.5rem"
                    propWidth32="1.5rem"
                    propWidth33="1.5rem"
                    propFlex="1"
                    propFlex1="1"
                    propFlex2="1"
                    propFlex3="1"
                    propFlex4="1"
                    propFlex5="1"
                    propFlex6="1"
                    propFlex7="1"
                    propFlex8="1"
                    propFlex9="1"
                    propFlex10="1"
                    propFlex11="1"
                    propFlex12="1"
                    propFlex13="1"
                    propFlex14="1"
                    propFlex15="1"
                    propFlex16="1"
                    propFlex17="1"
                    propFlex18="1"
                    propFlex19="1"
                    propFlex20="1"
                    propFlex21="1"
                    propFlex22="1"
                    propFlex23="1"
                    propFlex24="1"
                    propFlex25="1"
                    propFlex26="1"
                    propFlex27="1"
                    propFlex28="unset"
                    propFlex29="unset"
                    propFlex30="unset"
                    propFlex31="unset"
                    propFlex32="unset"
                    propFlex33="unset"
                    propBorderRadius="unset"
                    propBorderRadius1="2.5rem"
                    propBorderRadius2="unset"
                    propBorderRadius3="unset"
                    propBorderRadius4="unset"
                    propBorderRadius5="unset"
                    propBorderRadius6="unset"
                    propBorderRadius7="unset"
                    propBorderRadius8="unset"
                    propBorderRadius9="unset"
                    propBorderRadius10="unset"
                    propBorderRadius11="2.5rem"
                    propBorderRadius12="unset"
                    propBorderRadius13="unset"
                    propBorderRadius14="2.5rem"
                    propBorderRadius15="unset"
                    propBorderRadius16="2.5rem"
                    propBorderRadius17="unset"
                    propBorderRadius18="unset"
                    propBorderRadius19="unset"
                    propBorderRadius20="unset"
                    propBorderRadius21="unset"
                    propBorderRadius22="unset"
                    propBorderRadius23="unset"
                    propBorderRadius24="unset"
                    propBorderRadius25="2.5rem"
                    propBorderRadius26="unset"
                    propBorderRadius27="unset"
                    propBorderRadius28="unset"
                    propBorderRadius29="unset"
                    propBorderRadius30="unset"
                    propBorderRadius31="unset"
                    propBorderRadius32="unset"
                    propBorderRadius33="unset"
                    propBackgroundColor="unset"
                    propBackgroundColor1="#009ea0"
                    propBackgroundColor2="unset"
                    propBackgroundColor3="unset"
                    propBackgroundColor4="unset"
                    propBackgroundColor5="unset"
                    propBackgroundColor6="unset"
                    propBackgroundColor7="unset"
                    propBackgroundColor8="unset"
                    propBackgroundColor9="unset"
                    propBackgroundColor10="unset"
                    propBackgroundColor11="#009ea0"
                    propBackgroundColor12="unset"
                    propBackgroundColor13="unset"
                    propBackgroundColor14="#009ea0"
                    propBackgroundColor15="unset"
                    propBackgroundColor16="#009ea0"
                    propBackgroundColor17="unset"
                    propBackgroundColor18="unset"
                    propBackgroundColor19="unset"
                    propBackgroundColor20="unset"
                    propBackgroundColor21="unset"
                    propBackgroundColor22="unset"
                    propBackgroundColor23="unset"
                    propBackgroundColor24="unset"
                    propBackgroundColor25="#009ea0"
                    propBackgroundColor26="unset"
                    propBackgroundColor27="unset"
                    propBackgroundColor28="unset"
                    propBackgroundColor29="unset"
                    propBackgroundColor30="unset"
                    propBackgroundColor31="unset"
                    propBackgroundColor32="unset"
                    propBackgroundColor33="unset"
                    propOverflow="unset"
                    propOverflow1="hidden"
                    propOverflow2="unset"
                    propOverflow3="unset"
                    propOverflow4="unset"
                    propOverflow5="unset"
                    propOverflow6="unset"
                    propOverflow7="unset"
                    propOverflow8="unset"
                    propOverflow9="unset"
                    propOverflow10="unset"
                    propOverflow11="hidden"
                    propOverflow12="unset"
                    propOverflow13="unset"
                    propOverflow14="hidden"
                    propOverflow15="unset"
                    propOverflow16="hidden"
                    propOverflow17="unset"
                    propOverflow18="unset"
                    propOverflow19="unset"
                    propOverflow20="unset"
                    propOverflow21="unset"
                    propOverflow22="unset"
                    propOverflow23="unset"
                    propOverflow24="unset"
                    propOverflow25="hidden"
                    propOverflow26="unset"
                    propOverflow27="unset"
                    propOverflow28="unset"
                    propOverflow29="unset"
                    propOverflow30="unset"
                    propOverflow31="unset"
                    propOverflow32="unset"
                    propOverflow33="unset"
                    propColor="#3c3c3c"
                    propColor1="#fdfdfd"
                    propColor2="#3c3c3c"
                    propColor3="#3c3c3c"
                    propColor4="#3c3c3c"
                    propColor5="#3c3c3c"
                    propColor6="#3c3c3c"
                    propColor7="#3c3c3c"
                    propColor8="#3c3c3c"
                    propColor9="#3c3c3c"
                    propColor10="#3c3c3c"
                    propColor11="#fdfdfd"
                    propColor12="#3c3c3c"
                    propColor13="#3c3c3c"
                    propColor14="#fdfdfd"
                    propColor15="#3c3c3c"
                    propColor16="#fdfdfd"
                    propColor17="#3c3c3c"
                    propColor18="#3c3c3c"
                    propColor19="#3c3c3c"
                    propColor20="#3c3c3c"
                    propColor21="#3c3c3c"
                    propColor22="#3c3c3c"
                    propColor23="#3c3c3c"
                    propColor24="#3c3c3c"
                    propColor25="#fdfdfd"
                    propColor26="#3c3c3c"
                    propColor27="#3c3c3c"
                    propColor28="#3c3c3c"
                    propColor29="#3c3c3c"
                    propColor30="#3c3c3c"
                    propColor31="rgba(60, 60, 60, 0)"
                    propColor32="rgba(60, 60, 60, 0)"
                    propColor33="rgba(60, 60, 60, 0)"
                    propTextShadow="unset"
                    propTextShadow1="unset"
                    propTextShadow2="unset"
                    propTextShadow3="unset"
                    propTextShadow4="unset"
                    propTextShadow5="unset"
                    propTextShadow6="unset"
                    propTextShadow7="unset"
                    propTextShadow8="unset"
                    propTextShadow9="unset"
                    propTextShadow10="unset"
                    propTextShadow11="unset"
                    propTextShadow12="unset"
                    propTextShadow13="unset"
                    propTextShadow14="unset"
                    propTextShadow15="unset"
                    propTextShadow16="unset"
                    propTextShadow17="unset"
                    propTextShadow18="unset"
                    propTextShadow19="unset"
                    propTextShadow20="unset"
                    propTextShadow21="unset"
                    propTextShadow22="unset"
                    propTextShadow23="unset"
                    propTextShadow24="unset"
                    propTextShadow25="unset"
                    propTextShadow26="unset"
                    propTextShadow27="unset"
                    propTextShadow28="unset"
                    propTextShadow29="unset"
                    propTextShadow30="unset"
                    propTextShadow31="unset"
                    propTextShadow32="unset"
                    propTextShadow33="unset"
                    propTextDecoration="unset"
                    propTextDecoration1="unset"
                    propTextDecoration2="unset"
                    propTextDecoration3="unset"
                    propTextDecoration4="unset"
                    propTextDecoration5="unset"
                    propTextDecoration6="unset"
                    propTextDecoration7="unset"
                    propTextDecoration8="unset"
                    propTextDecoration9="unset"
                    propTextDecoration10="unset"
                    propTextDecoration11="unset"
                    propTextDecoration12="unset"
                    propTextDecoration13="unset"
                    propTextDecoration14="unset"
                    propTextDecoration15="none"
                    propTextDecoration16="none"
                    propTextDecoration17="unset"
                    propTextDecoration18="none"
                    propTextDecoration19="unset"
                    propTextDecoration20="unset"
                    propTextDecoration21="unset"
                    propTextDecoration22="unset"
                    propTextDecoration23="unset"
                    propTextDecoration24="unset"
                    propTextDecoration25="unset"
                    propTextDecoration26="unset"
                    propTextDecoration27="unset"
                    propTextDecoration28="unset"
                    propTextDecoration29="unset"
                    propTextDecoration30="unset"
                    propTextDecoration31="unset"
                    propTextDecoration32="unset"
                    propTextDecoration33="unset"
                  />
                  <Calendar
                    prop="травень"
                    prop1="1"
                    prop2="2"
                    prop3="3"
                    prop4="4"
                    prop5="5"
                    prop6="6"
                    prop7="7"
                    prop8="8"
                    prop9="9"
                    prop10="10"
                    prop11="11"
                    prop12="12"
                    prop13="13"
                    prop14="14"
                    prop15="15"
                    prop16="16"
                    prop17="17"
                    prop18="18"
                    prop19="19"
                    prop20="20"
                    prop21="21"
                    prop22="22"
                    prop23="23"
                    prop24="24"
                    prop25="25"
                    prop26="26"
                    prop27="27"
                    prop28="28"
                    prop29="29"
                    prop30="30"
                    prop31="31"
                    prop32="1"
                    prop33="1"
                    prop34="1"
                    propWidth="unset"
                    propWidth1="unset"
                    propWidth2="unset"
                    propWidth3="unset"
                    propWidth4="unset"
                    propWidth5="unset"
                    propWidth6="unset"
                    propWidth7="unset"
                    propWidth8="unset"
                    propWidth9="unset"
                    propWidth10="unset"
                    propWidth11="unset"
                    propWidth12="unset"
                    propWidth13="unset"
                    propWidth14="unset"
                    propWidth15="unset"
                    propWidth16="unset"
                    propWidth17="unset"
                    propWidth18="unset"
                    propWidth19="unset"
                    propWidth20="unset"
                    propWidth21="unset"
                    propWidth22="unset"
                    propWidth23="unset"
                    propWidth24="unset"
                    propWidth25="unset"
                    propWidth26="unset"
                    propWidth27="unset"
                    propWidth28="1.5rem"
                    propWidth29="1.5rem"
                    propWidth30="1.5rem"
                    propWidth31="1.5rem"
                    propWidth32="1.5rem"
                    propFlex="1"
                    propFlex1="1"
                    propFlex2="1"
                    propFlex3="1"
                    propFlex4="1"
                    propFlex5="1"
                    propFlex6="1"
                    propFlex7="1"
                    propFlex8="1"
                    propFlex9="1"
                    propFlex10="1"
                    propFlex11="1"
                    propFlex12="1"
                    propFlex13="1"
                    propFlex14="1"
                    propFlex15="1"
                    propFlex16="1"
                    propFlex17="1"
                    propFlex18="1"
                    propFlex19="1"
                    propFlex20="1"
                    propFlex21="1"
                    propFlex22="1"
                    propFlex23="1"
                    propFlex24="1"
                    propFlex25="1"
                    propFlex26="1"
                    propFlex27="1"
                    propFlex28="unset"
                    propFlex29="unset"
                    propFlex30="unset"
                    propFlex31="unset"
                    propFlex32="unset"
                    propBorderRadius="unset"
                    propBorderRadius1="unset"
                    propBorderRadius2="unset"
                    propBorderRadius3="unset"
                    propBorderRadius4="unset"
                    propBorderRadius5="unset"
                    propBorderRadius6="unset"
                    propBorderRadius7="unset"
                    propBorderRadius8="unset"
                    propBorderRadius9="unset"
                    propBorderRadius10="unset"
                    propBorderRadius11="unset"
                    propBorderRadius12="unset"
                    propBorderRadius13="unset"
                    propBorderRadius14="unset"
                    propBorderRadius15="unset"
                    propBorderRadius16="unset"
                    propBorderRadius17="unset"
                    propBorderRadius18="unset"
                    propBorderRadius19="unset"
                    propBorderRadius20="unset"
                    propBorderRadius21="unset"
                    propBorderRadius22="unset"
                    propBorderRadius23="unset"
                    propBorderRadius24="unset"
                    propBorderRadius25="unset"
                    propBorderRadius26="unset"
                    propBorderRadius27="unset"
                    propBorderRadius28="unset"
                    propBorderRadius29="unset"
                    propBorderRadius30="unset"
                    propBorderRadius31="unset"
                    propBorderRadius32="unset"
                    propBackgroundColor="unset"
                    propBackgroundColor1="unset"
                    propBackgroundColor2="unset"
                    propBackgroundColor3="unset"
                    propBackgroundColor4="unset"
                    propBackgroundColor5="unset"
                    propBackgroundColor6="unset"
                    propBackgroundColor7="unset"
                    propBackgroundColor8="unset"
                    propBackgroundColor9="unset"
                    propBackgroundColor10="unset"
                    propBackgroundColor11="unset"
                    propBackgroundColor12="unset"
                    propBackgroundColor13="unset"
                    propBackgroundColor14="unset"
                    propBackgroundColor15="unset"
                    propBackgroundColor16="unset"
                    propBackgroundColor17="unset"
                    propBackgroundColor18="unset"
                    propBackgroundColor19="unset"
                    propBackgroundColor20="unset"
                    propBackgroundColor21="unset"
                    propBackgroundColor22="unset"
                    propBackgroundColor23="unset"
                    propBackgroundColor24="unset"
                    propBackgroundColor25="unset"
                    propBackgroundColor26="unset"
                    propBackgroundColor27="unset"
                    propBackgroundColor28="unset"
                    propBackgroundColor29="unset"
                    propBackgroundColor30="unset"
                    propBackgroundColor31="unset"
                    propBackgroundColor32="unset"
                    propOverflow="unset"
                    propOverflow1="unset"
                    propOverflow2="unset"
                    propOverflow3="unset"
                    propOverflow4="unset"
                    propOverflow5="unset"
                    propOverflow6="unset"
                    propOverflow7="unset"
                    propOverflow8="unset"
                    propOverflow9="unset"
                    propOverflow10="unset"
                    propOverflow11="unset"
                    propOverflow12="unset"
                    propOverflow13="unset"
                    propOverflow14="unset"
                    propOverflow15="unset"
                    propOverflow16="unset"
                    propOverflow17="unset"
                    propOverflow18="unset"
                    propOverflow19="unset"
                    propOverflow20="unset"
                    propOverflow21="unset"
                    propOverflow22="unset"
                    propOverflow23="unset"
                    propOverflow24="unset"
                    propOverflow25="unset"
                    propOverflow26="unset"
                    propOverflow27="unset"
                    propOverflow28="unset"
                    propOverflow29="unset"
                    propOverflow30="unset"
                    propOverflow31="unset"
                    propOverflow32="unset"
                    propColor="#3c3c3c"
                    propColor1="#3c3c3c"
                    propColor2="#3c3c3c"
                    propColor3="#3c3c3c"
                    propColor4="#3c3c3c"
                    propColor5="#3c3c3c"
                    propColor6="#3c3c3c"
                    propColor7="#3c3c3c"
                    propColor8="#3c3c3c"
                    propColor9="#3c3c3c"
                    propColor10="#3c3c3c"
                    propColor11="#3c3c3c"
                    propColor12="#3c3c3c"
                    propColor13="#3c3c3c"
                    propColor14="#3c3c3c"
                    propColor15="#3c3c3c"
                    propColor16="#3c3c3c"
                    propColor17="#3c3c3c"
                    propColor18="#3c3c3c"
                    propColor19="#3c3c3c"
                    propColor20="#3c3c3c"
                    propColor21="#3c3c3c"
                    propColor22="#3c3c3c"
                    propColor23="#3c3c3c"
                    propColor24="#3c3c3c"
                    propColor25="#3c3c3c"
                    propColor26="#3c3c3c"
                    propColor27="#3c3c3c"
                    propColor28="#3c3c3c"
                    propColor29="#3c3c3c"
                    propColor30="#3c3c3c"
                    propColor31="rgba(60, 60, 60, 0)"
                    propColor32="rgba(60, 60, 60, 0)"
                    propTextShadow="unset"
                    propTextShadow1="unset"
                    propTextShadow2="unset"
                    propTextShadow3="unset"
                    propTextShadow4="unset"
                    propTextShadow5="unset"
                    propTextShadow6="unset"
                    propTextShadow7="unset"
                    propTextShadow8="unset"
                    propTextShadow9="unset"
                    propTextShadow10="unset"
                    propTextShadow11="unset"
                    propTextShadow12="unset"
                    propTextShadow13="unset"
                    propTextShadow14="unset"
                    propTextShadow15="unset"
                    propTextShadow16="unset"
                    propTextShadow17="unset"
                    propTextShadow18="unset"
                    propTextShadow19="unset"
                    propTextShadow20="unset"
                    propTextShadow21="unset"
                    propTextShadow22="unset"
                    propTextShadow23="unset"
                    propTextShadow24="unset"
                    propTextShadow25="unset"
                    propTextShadow26="unset"
                    propTextShadow27="unset"
                    propTextShadow28="unset"
                    propTextShadow29="unset"
                    propTextShadow30="unset"
                    propTextShadow31="unset"
                    propTextShadow32="unset"
                    propTextDecoration="unset"
                    propTextDecoration1="unset"
                    propTextDecoration2="unset"
                    propTextDecoration3="unset"
                    propTextDecoration4="unset"
                    propTextDecoration5="unset"
                    propTextDecoration6="unset"
                    propTextDecoration7="unset"
                    propTextDecoration8="unset"
                    propTextDecoration9="unset"
                    propTextDecoration10="unset"
                    propTextDecoration11="unset"
                    propTextDecoration12="unset"
                    propTextDecoration13="unset"
                    propTextDecoration14="unset"
                    propTextDecoration15="none"
                    propTextDecoration16="none"
                    propTextDecoration17="unset"
                    propTextDecoration18="none"
                    propTextDecoration19="unset"
                    propTextDecoration20="unset"
                    propTextDecoration21="unset"
                    propTextDecoration22="unset"
                    propTextDecoration23="unset"
                    propTextDecoration24="unset"
                    propTextDecoration25="unset"
                    propTextDecoration26="unset"
                    propTextDecoration27="unset"
                    propTextDecoration28="unset"
                    propTextDecoration29="unset"
                    propTextDecoration30="unset"
                    propTextDecoration31="unset"
                    propTextDecoration32="unset"
                  />
                </div>
                <div className="self-stretch flex flex-row items-start justify-center py-[0rem] pl-[1.25rem] pr-[1.375rem]">
                  <img
                    className="h-[2rem] w-[2rem] relative object-contain z-[1]"
                    loading="lazy"
                    alt=""
                    src="/actions--navigation--chevronleft--34@2x.png"
                  />
                </div>
              </div>
            </div>
          </div>
          <Footer />
        </section>
      </main>
      <div className="w-[67.125rem] flex flex-row items-start justify-center max-w-full shrink-0">
        <img
          className="h-[1.5rem] w-[1.5rem] relative object-contain shrink-0"
          alt=""
          src="/actions--navigation--chevronright--24@2x.png"
        />
      </div>
    </div>
  );
};

export default Frame5;
