namespace Trendlink.Domain.Users
{
    public enum AccountCategory
    {
        None = 0,
        CookingAndFood = 1,
        FashionAndStyle = 2,
        ClothingAndFootwear = 3,
        Horticulture = 4,
        Animals = 5,
        Cryptocurrency = 6,
        Technology = 7,
        Travel = 8,
        Education = 9,
        Fitness = 10,
        Art = 11,
        Photography = 12,
        Music = 13,
        Sports = 14,
        HealthAndWellness = 15,
        Gaming = 16,
        Parenting = 17,
        DIYAndCrafts = 18,
        Literature = 19,
        Science = 20,
        History = 21,
        News = 22,
        Politics = 23,
        Finance = 24,
        Environment = 25,
        RealEstate = 26,
        Automobiles = 27,
        MoviesAndTV = 28,
        Comedy = 29,
        HomeDecor = 30,
        Relationships = 31,
        SelfImprovement = 32,
        Entrepreneurship = 33,
        LegalAdvice = 34,
        Marketing = 35,
        MentalHealth = 36,
        PersonalDevelopment = 37,
        ReligionAndSpirituality = 38,
        SocialMedia = 39
    }
}
