import { FunctionComponent } from "react";
import Component6 from "./Component6";
import {MenuType} from "../types/MenuType";

const Menu: FunctionComponent<MenuType> = ({
  className = "",
  prop,
  prop1,
  prop2,
  prop3,
  prop4,
  prop5,
  prop6,
  prop7,
  prop8,
  prop9,
  prop10,
  prop11,
  prop12,
  prop13,
  prop14,
  prop15,
  prop16,
  prop17,
  prop18,
  prop19,
  prop110,
  prop111,
  prop112,
  prop113,
  propAlignSelf,
  propAlignSelf1,
  propAlignSelf2,
  propAlignSelf3,
  propAlignSelf4,
  propAlignSelf5,
  propAlignSelf6,
  propAlignSelf7,
  propAlignSelf8,
  propAlignSelf9,
  propAlignSelf10,
  propAlignSelf11,
  propOverflow,
  propOverflow1,
  propOverflow2,
  propOverflow3,
  propOverflow4,
  propOverflow5,
  propOverflow6,
  propOverflow7,
  propOverflow8,
  propOverflow9,
  propOverflow10,
  propOverflow11,
  propFlex,
  propFlex1,
  propFlex2,
  propFlex3,
  propFlex4,
  propFlex5,
  propFlex6,
  propFlex7,
  propFlex8,
  propFlex9,
  propFlex10,
  propFlex11,
  propOverflow12,
  propOverflow13,
  propOverflow14,
  propOverflow15,
  propOverflow16,
  propOverflow17,
  propOverflow18,
  propOverflow19,
  propOverflow110,
  propOverflow111,
  propOverflow112,
  propOverflow113,
  propHeight,
  propHeight1,
  propHeight2,
  propHeight3,
  propHeight4,
  propHeight5,
  propHeight6,
  propHeight7,
  propHeight8,
  propHeight9,
  propHeight10,
  propHeight11,
  propWidth,
  propWidth1,
  propWidth2,
  propWidth3,
  propWidth4,
  propWidth5,
  propWidth6,
  propWidth7,
  propWidth8,
  propWidth9,
  propWidth10,
  propWidth11,
}) => {
  return (
    <div
      className={`w-[345px] !m-[0] absolute top-[166px] left-[-500px] flex flex-col items-end justify-start gap-5 max-w-full z-[2] text-left text-base text-white font-inter ${className}`}
    >
      <Component6
        propAlignSelf={propAlignSelf}
        propOverflow={propOverflow}
        propFlex={propFlex}
        prop={prop}
        propOverflow1={propOverflow12}
        propHeight={propHeight}
        prop1={prop12}
        propWidth={propWidth}
      />
      <Component6
        propAlignSelf={propAlignSelf1}
        propOverflow={propOverflow1}
        propFlex={propFlex1}
        prop={prop1}
        propOverflow1={propOverflow13}
        propHeight={propHeight1}
        prop1={prop13}
        propWidth={propWidth1}
      />
      <Component6
        propAlignSelf={propAlignSelf2}
        propOverflow={propOverflow2}
        propFlex={propFlex2}
        prop={prop2}
        propOverflow1={propOverflow14}
        propHeight={propHeight2}
        prop1={prop14}
        propWidth={propWidth2}
      />
      <Component6
        propAlignSelf={propAlignSelf3}
        propOverflow={propOverflow3}
        propFlex={propFlex3}
        prop={prop3}
        propOverflow1={propOverflow15}
        propHeight={propHeight3}
        prop1={prop15}
        propWidth={propWidth3}
      />
      <Component6
        propAlignSelf={propAlignSelf4}
        propOverflow={propOverflow4}
        propFlex={propFlex4}
        prop={prop4}
        propOverflow1={propOverflow16}
        propHeight={propHeight4}
        prop1={prop16}
        propWidth={propWidth4}
      />
      <Component6
        propAlignSelf={propAlignSelf5}
        propOverflow={propOverflow5}
        propFlex={propFlex5}
        prop={prop5}
        propOverflow1={propOverflow17}
        propHeight={propHeight5}
        prop1={prop17}
        propWidth={propWidth5}
      />
      <div className="self-stretch flex flex-row items-start justify-end py-0 pl-0 pr-px box-border max-w-full">
        <Component6
          propAlignSelf={propAlignSelf6}
          propOverflow={propOverflow6}
          propFlex={propFlex6}
          prop={prop6}
          propOverflow1={propOverflow18}
          propHeight={propHeight6}
          prop1={prop18}
          propWidth={propWidth6}
        />
      </div>
      <Component6
        propAlignSelf={propAlignSelf7}
        propOverflow={propOverflow7}
        propFlex={propFlex7}
        prop={prop7}
        propOverflow1={propOverflow19}
        propHeight={propHeight7}
        prop1={prop19}
        propWidth={propWidth7}
      />
      <Component6
        propAlignSelf={propAlignSelf8}
        propOverflow={propOverflow8}
        propFlex={propFlex8}
        prop={prop8}
        propOverflow1={propOverflow110}
        propHeight={propHeight8}
        prop1={prop110}
        propWidth={propWidth8}
      />
      <Component6
        propAlignSelf={propAlignSelf9}
        propOverflow={propOverflow9}
        propFlex={propFlex9}
        prop={prop9}
        propOverflow1={propOverflow111}
        propHeight={propHeight9}
        prop1={prop111}
        propWidth={propWidth9}
      />
      <Component6
        propAlignSelf={propAlignSelf10}
        propOverflow={propOverflow10}
        propFlex={propFlex10}
        prop={prop10}
        propOverflow1={propOverflow112}
        propHeight={propHeight10}
        prop1={prop112}
        propWidth={propWidth10}
      />
      <Component6
        propAlignSelf={propAlignSelf11}
        propOverflow={propOverflow11}
        propFlex={propFlex11}
        prop={prop11}
        propOverflow1={propOverflow113}
        propHeight={propHeight11}
        prop1={prop113}
        propWidth={propWidth11}
      />
    </div>
  );
};

export default Menu;
