services:
  trendlink.api:
    image: ${DOCKER_REGISTRY-}trendlinkapi
    container_name: Trendlink.Api
    build:
      context: .
      dockerfile: src/Trendlink.Api/Dockerfile
    depends_on:
     - trendlink-db
  
  trendlink-db:
    image: postgres:latest
    container_name: Trendlink.Db
    environment:
      - POSTGRES_DB=trendlink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
   
  trendlink-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Trendlink.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/trendlink-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080

  trendlink-seq:
    image: datalust/seq:latest
    container_name: Trendlink.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  trendlink-redis:
    image: redis:latest
    container_name: Trendlink.Redis
    restart: always
    ports:
      - '6379:6379'