name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.x"
  SOLUTION_PATH: "./Trendlink.sln"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # Remove compose proj from sln
      - name: Remove compose proj from sln
        run: dotnet sln ${{ env.SOLUTION_PATH }} remove $(dotnet sln ${{ env.SOLUTION_PATH }} list | grep .dcproj)
      
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      # Add compose proj back to sln
      - name: Add compose proj back to sln
        run: |
          find . -name '*.dcproj' | xargs -I {} dotnet sln ${{ env.SOLUTION_PATH }} add {}
        
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      # Remove integration tests from sln
      - name: Remove Trendlinl.Application.IntegrationTests from sln
        run: dotnet sln ${{ env.SOLUTION_PATH }} remove $(dotnet sln ${{ env.SOLUTION_PATH }} list | grep .IntegrationTests.scproj)
      
      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build

      # Add integration tests back to sln
      - name: Add Trendlinl.Application.IntegrationTests back to sln
        run: |
          find . -name '*.IntegrationTests.scproj' | xargs -I {} dotnet sln ${{ env.SOLUTION_PATH }} add {}
        
      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build
